version: '3.4'
services:
    db:
        image: postgres
        environment:
          POSTGRES_PASSWORD: "!mYLittleAccount"
        ports:
          - "5432:5432"
    account:
        image: account
        restart: always
        environment:
          TZ: America/Sao_Paulo
        ports:
          - "8080:8080"
        command: mvn spring-boot:run
        links:
          - db
        depends_on:
          - db
        networks:
          - account-network
networks:
    account-network:
        driver: bridge